#cloud-config

packages:
 - ntp
 - qemu-guest-agent
 
runcmd:
  - curl https://releases.rancher.com/install-docker/20.10.sh | sh

groups:
  - docker

users:
  - name: ubuntu
    groups: docker
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCvanB0m751u7unkvMdDiRYrD34pp86f68k2f0g4gElkWvCF7PqkM5s7dOfltN1cyWZIm8adxZhdxhq4oHYKtMqD/JzSrmShdmJ0CaRGF5YjkcWkGygu9YlEgevP3iz4yxAMshv2rNz9GhJVlonEHorrVUovZvQBiLw7Laxu3rQOhin2engiM0NqaEMAsUyc97IrMHj7ehPrBIRuGaLH8kNVSCYgTFsZq6ujpHaLMBPAu35y88DI5kwHHXDdiT3k/ubTJJL1R5HarLhtVk2koPzT6CXHd2+/VDogzASOLYP/Ih/+pYwztutxBs+ihIidyxTvPyzNpVb5UVL9CNZt5eb julien@laptop

# write_files:
#   - path: "/etc/environment"
#     append: true
#     content: |
#       export HTTP_PROXY="http://192.168.11.1:3128"
#       export HTTPS_PROXY="https://192.168.11.1:3129"
      
ca-certs:
  trusted: 
  - | 
    -----BEGIN CERTIFICATE-----
    MIIGETCCA/mgAwIBAgIIWYY0TjMMc8cwDQYJKoZIhvcNAQELBQAwXzEQMA4GA1UE
    AxMHcGZzZW5zZTELMAkGA1UEBhMCQ0ExCzAJBgNVBAgTAlFDMRAwDgYDVQQHEwdO
    ZXdwb3J0MRIwEAYDVQQKEwlMb2NhY2xvdWQxCzAJBgNVBAsTAklUMB4XDTIyMDIw
    NDIyMzU0NloXDTMyMDIwMjIyMzU0NlowXzEQMA4GA1UEAxMHcGZzZW5zZTELMAkG
    A1UEBhMCQ0ExCzAJBgNVBAgTAlFDMRAwDgYDVQQHEwdOZXdwb3J0MRIwEAYDVQQK
    EwlMb2NhY2xvdWQxCzAJBgNVBAsTAklUMIICIjANBgkqhkiG9w0BAQEFAAOCAg8A
    MIICCgKCAgEA3d74+Upvy+sey9zGuM686X4N13PJmaedPsq2bF/4jjqXaVjseXqb
    7b5ECUoHKB+zjvOXhF+oQKEE/E2iP5sRDydnIlG8GBaTSnAcOJlMOyqjU+xSku4U
    uR4yItmuxxSyZ5DwfH8e1SrOSTXRDNynqe3MmCZrjmYo64ry4gqPk0UO5LjtRxGP
    xC0vDgqq7rVteAOQtxSgCQA+SrzPi5zU/NTrI9KcfQdBjhAvsqwE1F4x1OVvBguL
    KMQcKiPnk84YXLYBCciQh6rjUtpfsZ4WSgw8r7Hw6y1mGXbiLYaQflXgca9POMpc
    izcG5tRtEPNMzPyWa0G2qRXhEzhsc1wTRpk/B7s1dkOfE+fMtfePILZL7GHcrCPq
    88oxZsK+DES2e4q2gOjyheF6Pa/Ch9jdC3C0CpU74oAvWXi4Z2XYBAmqY7doQA2r
    nOOmuNoa3fWsdnrYvBQEmJsEuPbF6neXKHDLNnuXYt32VVyQSfBpuXYJmuvDpe5U
    1vX5ShUz/IHZ9LY3nV5mxxIqih/IO19c76kzAlj+p7LMYccmGH75EXZUsRNX9MLM
    QHQjx9bdOXACtLpB50EAAnUBb8MkWKsngMI6HOduelD7ajGMsVgShnzL1VkvvyNM
    06Om0YCOf0i/omhHDPVj3r8GUnVqyHkoCieSIvhCozh7KhUoswbS7XMCAwEAAaOB
    0DCBzTAdBgNVHQ4EFgQUnrVUKu3S7rgJNiSvHCyKCREXaOowgZAGA1UdIwSBiDCB
    hYAUnrVUKu3S7rgJNiSvHCyKCREXaOqhY6RhMF8xEDAOBgNVBAMTB3Bmc2Vuc2Ux
    CzAJBgNVBAYTAkNBMQswCQYDVQQIEwJRQzEQMA4GA1UEBxMHTmV3cG9ydDESMBAG
    A1UEChMJTG9jYWNsb3VkMQswCQYDVQQLEwJJVIIIWYY0TjMMc8cwDAYDVR0TBAUw
    AwEB/zALBgNVHQ8EBAMCAQYwDQYJKoZIhvcNAQELBQADggIBADvaCLj84a7x8rPG
    B3dgIJCf1GOHLPNUbw6+8Z7x0n2kSq/Az5v6R0qDNA+Pnf1aUBlJNSelTtkUJlTy
    UsmcDMsasdKZqVqd+K0x93A9p6LL3s36qhndh7odWdyXZBbSE9HCfWNRYq0IVzRe
    q41+kIy81tw+m+Gh1zsX2CdcRCGaNI7OmjayNYC3YY7Y370GXPbDXNgzvKCoHwJZ
    Fh0MYMNKPts7NDT/GfS/htBXaxM5rg1sdU/zyuQ1vrVr3BcNpc9Rla7te3qFa7F3
    u13ZEEb0Qk5XV3NonxzRS2/fE1jlX3Zv9mgDb8S4/MQcM4YRJSUMnL9RHYeWYp0B
    9okx38tjDBkhdUxbw9OSbTAtcWr9L+0Gcjn8CqMHdGiImN685scD1WOC5ZLKuxR7
    gupdkZCump+qVzpV7nixZxBIXT5ygVrgyGW0dMOjFchzhX63XVb2dxBnislwZUhv
    Xxl9pMTRzKZ8PyvtUmZ55RrYyIa061h4hMPT4VS0uGAtWY1wpG9b3LEbIpn5DiC0
    gOP8p4qwvvyUFatqbEI0vNqEVQ5s4ClkNthgOH1cNO5Q4h3GIFYzE9X9ftCeOwS1
    yRNMHLx0LpJF086m2kfB3dwgZVVfgVNJ2wci40dDWkYQB/Yv/wdRaMKcsUVC0iLJ
    w4nlOUleSEKwfDrbFE8dHTkPeiHK
    -----END CERTIFICATE-----

disk_setup:
  /dev/vdb:
    table_type: gpt
    layout: True
    overwrite: True

fs_setup:
  - device: /dev/vdb
    filesystem: ext4
    partition: 1

mounts:
  - [ /dev/vdb1, ${mount}, auto, "defaults,noexec" ]
