#cloud-config

packages:
 - ntp
 - qemu-guest-agent
 
runcmd:
  - curl https://releases.rancher.com/install-docker/20.10.sh | sh

groups:
  - docker

users:
  - name: ubuntu
    groups: docker
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCvanB0m751u7unkvMdDiRYrD34pp86f68k2f0g4gElkWvCF7PqkM5s7dOfltN1cyWZIm8adxZhdxhq4oHYKtMqD/JzSrmShdmJ0CaRGF5YjkcWkGygu9YlEgevP3iz4yxAMshv2rNz9GhJVlonEHorrVUovZvQBiLw7Laxu3rQOhin2engiM0NqaEMAsUyc97IrMHj7ehPrBIRuGaLH8kNVSCYgTFsZq6ujpHaLMBPAu35y88DI5kwHHXDdiT3k/ubTJJL1R5HarLhtVk2koPzT6CXHd2+/VDogzASOLYP/Ih/+pYwztutxBs+ihIidyxTvPyzNpVb5UVL9CNZt5eb julien@laptop
